""" Parameter spaces used for Bayesian optimization of the different classifier parameters. """

from skopt.space import Real, Integer

C_standard_space = [Real(0.0, 1.0, prior='uniform', name='mu'),
                    Real(0.4, 1.4, prior='uniform', name='spectral_radius'),
                    Real(0.4, 1.4, prior='uniform', name='W_in_scale'),
                    Real(0.4, 1.4, prior='uniform', name='bias_scale'),
                    Real(0.01, 1.0, prior='uniform', name='leaking_rate'),
                    Integer(5, 25, 'uniform', name='reservoir_dim')]

C_reduced_space = [Real(0.0, 1.0, prior='uniform', name='mu'),
                   Real(0.01, 2.0, prior='uniform', name='spectral_radius'),
                   Real(0.01, 2.0, prior='uniform', name='W_in_scale'),
                   Real(0.01, 2.0, prior='uniform', name='bias_scale'),
                   Real(0.01, 1.0, prior='uniform', name='leaking_rate'),
                   Integer(5, 500, 'uniform', name='reservoir_dim')]

C_combined_space = [Real(0.0, 1.0, prior='uniform', name='mu'),
                    Real(0.01, 2.0, prior='uniform', name='spectral_radius'),
                    Real(0.01, 2.0, prior='uniform', name='W_in_scale'),
                    Real(0.01, 2.0, prior='uniform', name='bias_scale'),
                    Real(0.01, 1.0, prior='uniform', name='leaking_rate'),
                    Integer(5, 500, 'uniform', name='reservoir_dim')]

C_tubes_space = [Real(0.0, 1.0, prior='uniform', name='mu'),
                 Real(0.01, 2.0, prior='uniform', name='spectral_radius'),
                 Real(0.01, 2.0, prior='uniform', name='W_in_scale'),
                 Real(0.01, 2.0, prior='uniform', name='bias_scale'),
                 Real(0.01, 1.0, prior='uniform', name='leaking_rate'),
                 Integer(5, 150, 'uniform', name='reservoir_dim')]

C_reservoir_space = [Real(0.01, 2.0, prior='uniform', name='spectral_radius'),
                     Real(0.01, 2.0, prior='uniform', name='W_in_scale'),
                     Real(0.01, 2.0, prior='uniform', name='bias_scale'),
                     Real(0.01, 1.0, prior='uniform', name='leaking_rate'),
                     Integer(5, 150, 'uniform', name='reservoir_dim')]

C_forecast_space = [Real(0.01, 2.0, prior='uniform', name='spectral_radius'),
                    Real(0.01, 2.0, prior='uniform', name='W_in_scale'),
                    Real(0.01, 2.0, prior='uniform', name='bias_scale'),
                    Real(0.01, 1.0, prior='uniform', name='leaking_rate'),
                    Integer(5, 150, 'uniform', name='reservoir_dim'),
                    Real(0.0001, 10.0, prior='log-uniform', name='beta')]

ESN_forecast_space = [Real(0.01, 2.0, prior='uniform', name='spectral_radius'),
                      Real(0.01, 2.0, prior='uniform', name='W_in_scale'),
                      Real(0.01, 2.0, prior='uniform', name='bias_scale'),
                      Real(0.01, 1.0, prior='uniform', name='leaking_rate'),
                      Integer(5, 500, 'uniform', name='reservoir_dim'),
                      Real(0.0001, 10.0, prior='log-uniform', name='beta')]

ESN_class_label_space = [Real(0.01, 2.0, prior='uniform', name='spectral_radius'),
                         Real(0.01, 2.0, prior='uniform', name='W_in_scale'),
                         Real(0.01, 2.0, prior='uniform', name='bias_scale'),
                         Real(0.01, 1.0, prior='uniform', name='leaking_rate'),
                         Integer(5, 500, 'uniform', name='reservoir_dim'),
                         Real(0.0001, 10.0, prior='log-uniform', name='beta')]

C_standard_aperture_space = [Real(3.5, 10.5, prior='log-uniform', name='pa1'),
                             Real(26.0, 78.0, prior='log-uniform', name='pa2'),
                             Real(70.0, 210.0, prior='log-uniform', name='pa3'),
                             Real(111.0, 333.0, prior='log-uniform', name='pa4'),
                             Real(8.0, 24.0, prior='log-uniform', name='pa5'),
                             Real(1.1, 2.5, prior='log-uniform', name='pa6'),
                             Real(25.0, 75.0, prior='log-uniform', name='pa7'),
                             Real(3.0, 9.0, prior='log-uniform', name='pa8'),
                             Real(50.0, 150.0, prior='log-uniform', name='pa9'),
                             Real(9.0, 27.0, prior='log-uniform', name='pa10'),
                             Real(20.0, 40.0, prior='log-uniform', name='pa11'),
                             Real(750.0, 2250.0, prior='log-uniform', name='pa12'),
                             Real(11.0, 33.0, prior='log-uniform', name='pa13'),
                             Real(6.0, 18.0, prior='log-uniform', name='pa14'),
                             Real(1710.0, 2110.0, prior='uniform', name='na1'),
                             Real(1710.0, 2110.0, prior='uniform', name='na2'),
                             Real(1848.0, 2248.0, prior='uniform', name='na3'),
                             Real(1710.0, 2110.0, prior='uniform', name='na4'),
                             Real(1710.0, 2110.0, prior='uniform', name='na5'),
                             Real(1710.0, 2110.0, prior='uniform', name='na6'),
                             Real(1710.0, 2110.0, prior='uniform', name='na7'),
                             Real(1710.0, 2110.0, prior='uniform', name='na8'),
                             Real(1710.0, 2110.0, prior='uniform', name='na9'),
                             Real(1710.0, 2110.0, prior='uniform', name='na10'),
                             Real(1710.0, 2110.0, prior='uniform', name='na11'),
                             Real(1582.0, 1982.0, prior='uniform', name='na12'),
                             Real(1710.0, 2110.0, prior='uniform', name='na13'),
                             Real(1710.0, 2110.0, prior='uniform', name='na14')]

C_reduced_aperture_space = [Real(7.0, 21.0, prior='uniform', name='pa1'),
                            Real(30.0, 90.0, prior='uniform', name='pa2'),
                            Real(65.0, 195.0, prior='uniform', name='pa3'),
                            Real(90.0, 270.0, prior='uniform', name='pa4'),
                            Real(17.0, 51.0, prior='uniform', name='pa5'),
                            Real(1.1, 3.0, prior='uniform', name='pa6'),
                            Real(35.0, 105.0, prior='uniform', name='pa7'),
                            Real(8.0, 27.0, prior='uniform', name='pa8'),
                            Real(130.0, 390.0, prior='uniform', name='pa9'),
                            Real(20.0, 60.0, prior='uniform', name='pa10'),
                            Real(20.0, 60.0, prior='uniform', name='pa11'),
                            Real(170.0, 510.0, prior='uniform', name='pa12'),
                            Real(18.0, 54.0, prior='uniform', name='pa13'),
                            Real(10.0, 30.0, prior='uniform', name='pa14'),
                            Real(160.0, 200.0, prior='uniform', name='na1'),
                            Real(175.0, 215.0, prior='uniform', name='na2'),
                            Real(175.0, 215.0, prior='uniform', name='na3'),
                            Real(175.0, 215.0, prior='uniform', name='na4'),
                            Real(160.0, 200.0, prior='uniform', name='na5'),
                            Real(160.0, 200.0, prior='uniform', name='na6'),
                            Real(160.0, 200.0, prior='uniform', name='na7'),
                            Real(160.0, 200.0, prior='uniform', name='na8'),
                            Real(160.0, 200.0, prior='uniform', name='na9'),
                            Real(160.0, 200.0, prior='uniform', name='na10'),
                            Real(175.0, 215.0, prior='uniform', name='na11'),
                            Real(160.0, 200.0, prior='uniform', name='na12'),
                            Real(175.0, 215.0, prior='uniform', name='na13'),
                            Real(160.0, 200.0, prior='uniform', name='na14')]

C_combined_aperture_space = [Real(85.0, 255.0, prior='uniform', name='pa1'),
                             Real(45.0, 135.0, prior='uniform', name='pa2'),
                             Real(40.0, 120.0, prior='uniform', name='pa3'),
                             Real(35.0, 105.0, prior='uniform', name='pa4'),
                             Real(65.0, 195.0, prior='uniform', name='pa5'),
                             Real(50.0, 150.0, prior='uniform', name='pa6'),
                             Real(40.0, 120.0, prior='uniform', name='pa7'),
                             Real(135.0, 410.0, prior='uniform', name='pa8'),
                             Real(55.0, 165.0, prior='uniform', name='pa9'),
                             Real(65.0, 195.0, prior='uniform', name='pa10'),
                             Real(35.0, 105.0, prior='uniform', name='pa11'),
                             Real(40.0, 120.0, prior='uniform', name='pa12'),
                             Real(50.0, 150.0, prior='uniform', name='pa13'),
                             Real(60.0, 180.0, prior='uniform', name='pa14'),
                             Real(55.0, 75.0, prior='uniform', name='na1'),
                             Real(55.0, 75.0, prior='uniform', name='na2'),
                             Real(55.0, 75.0, prior='uniform', name='na3'),
                             Real(55.0, 75.0, prior='uniform', name='na4'),
                             Real(50.0, 70.0, prior='uniform', name='na5'),
                             Real(55.0, 75.0, prior='uniform', name='na6'),
                             Real(55.0, 75.0, prior='uniform', name='na7'),
                             Real(50.0, 70.0, prior='uniform', name='na8'),
                             Real(50.0, 70.0, prior='uniform', name='na9'),
                             Real(50.0, 70.0, prior='uniform', name='na10'),
                             Real(55.0, 75.0, prior='uniform', name='na11'),
                             Real(50.0, 70.0, prior='uniform', name='na12'),
                             Real(55.0, 75.0, prior='uniform', name='na13'),
                             Real(55.0, 75.0, prior='uniform', name='na14')]
